Feat add credit test
comparison-of-banking-products/cobp-backend pull request #115
Opened 2024-01-09 00:24 UTC by MaximKostyolov

2024-01-09 08:42 UTC, alex-blag requested changes

2024-01-09 08:42 UTC, alex-blag commented on src/main/java/ru/cobp/backend/dto/credit/CreditDto.java
> +    private String banksBic;
bankBic

2024-01-09 08:42 UTC, alex-blag commented on src/main/java/ru/cobp/backend/dto/credit/NewCreditDto.java
> +    private String banksBic;
bankBic

2024-01-09 08:42 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +    @SneakyThrows
Уточни, зачем @SneakyThrows?

2024-01-09 08:42 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +                .toCreditResponseDto(TestUtils.buildGazprombankCredit()));
По-моему, перестарался. не нужно делать метод to... сразу создай нужный объект

2024-01-09 08:42 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +        when(creditMapper.toCreditResponseDtos(anyList())).thenReturn(expectedList);
маппер здесь тоже лишний, по идее тестирование мапперов будет в отдельных классах, просто изпользуй anyList

2024-01-09 08:42 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +                .getContentAsString(StandardCharsets.UTF_8);
уточни, не совсем понял значем так сложно проверять, в контроллере тебе надо убедиться в получении корректного кода и тела ответа, в виде жсона, а в теле ответа, по идее, достаточно проверить одно поле

маппинг, сервисы и репо надо тестировать в отдельных классах, чтобы максимально упростить тестируемое

2024-01-10 21:12 UTC, MaximKostyolov commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +    @SneakyThrows
Метод writeValueAsString() может выбросить JsonProcessingException. Поэтому нас учили использовать аннотацию @SneakyThrows при тестировании контроллеров

2024-01-10 21:18 UTC, MaximKostyolov commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +                .toCreditResponseDto(TestUtils.buildGazprombankCredit()));
Этот метод используется для конвертации 2-х кредитов в дто: 1) обычный, который создается в методе buildGazprombankCredit(); 2) обновленный кредит для тестирования метода update(), который создается в методе buildGazprombankUpdatedCredit(). Поэтому вместо создания 2-х дто в двух разных методах я использовал один метод toCreditResponseDto(Credit credit)

2024-01-10 21:21 UTC, MaximKostyolov commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +        when(creditMapper.toCreditResponseDtos(anyList())).thenReturn(expectedList);
Здесь вместо маппера стоит заглушка (@MockBean CreditMapper creditMapper). Я не тестирую маппер, просто настраиваю то, что вернет мне маппер при обращении к его методу

2024-01-10 21:31 UTC, MaximKostyolov commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +                .getContentAsString(StandardCharsets.UTF_8);
Да, так и есть. В этом тесте я проверяю код ответа и тело (достаточно наверно и одного поля, но нас учили так - поэтому полностью проверяю полученное тело ответа и то что я планирую получить). Вместо маппера и сервиса у меня заглушки - я настраиваю то, что я хочу получить при вызове их методов. 
Здесь verify(creditService).getById(creditId) - я проверяю, то что контроллер корректно отработал и вызывал метод creditService.getById(creditId)

2024-01-11 13:38 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +                .toCreditResponseDto(TestUtils.buildGazprombankCredit()));
Так и зачем такой огород городить? :) Почему не сделать так:
List<CreditResponseDto> expectedList = TestUtils.buildCreditResponseDtos();

2024-01-12 12:24 UTC, alex-blag approved these changes

2024-01-12 12:34 UTC, alex-blag approved these changes

2024-01-12 12:34 UTC, alex-blag approved these changes

2024-01-15 07:21 UTC, merged

2024-01-15 11:19 UTC, nkorzh reviewed
про тесты:

Тесты

Имена тестов должны описывать поведение тестируемого объекта и условия для проявления такого поведения. В идеале список имен тестов должен служить краткой документацией к тестируемому классу/endpoint-у.
Тело тестовых методов разделяем комментариями на три части: given (подготовка тестируемых объектов и тестовых данных), when (вызов тестируемого поведения), then (проверки)

Допускается объединять when и then (например, когда тестируется выброс исключения), например:
    @Test
    void getCoefficientShouldThrowWhen…() {
        // given
        var coefficient = aCoefficient(); 
        givenCoefficient(coefficient);

        // when / then
        assertThatThrownBy(() -> service.getCoefficient(…))
            .isInstanceOf(IllegalStateException.class)
            .hasMessage(“…”);
    }

Форматы имени теста 

should<действие>When<условия>, например: shouldThrowWhenMoonIsFull
Если в одном файле тестируется много разных методов класса, и из названия теста вида should<действие>When<условия> не очевидно, какой метод используется, можно указывать имя метода, например:
checkConfirmationCodeShouldThrowWhenMoonIsFull, getOrderHistoryShouldProvideOnlyEvenCheckpointsWhenMoonIsFull

2024-01-15 11:19 UTC, nkorzh commented on src/main/java/ru/cobp/backend/controller/credit/CreditController.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by("rate").ascending());
логику пагинации стоит класть в сервис а не в контроллер
в контроллере только верхнеуровневая передача ответственности сервису, он не думает про тип сортировки и не собирает внутри себя Pageable

2024-01-15 11:19 UTC, nkorzh commented on src/test/java/ru/cobp/backend/controller/credit/CreditControllerTest.java
> +public class CreditControllerTest {
названия тестов в этом классе не очень
скину FAQ в беседу