Fix: банковские сервисы
comparison-of-banking-products/cobp-backend pull request #129
Opened 2024-01-11 17:45 UTC by mdemidkin1992

Начал отработку комментов, в основном коснулся банков: 

* Доработаны недостающие методы по сервису BankServiceImpl
* Добавлены сваггер аннотации для BankController
* Перенесем маппинг из сервиса в контроллер
* Исправлен нейминг для NewBankDto (теперь это более понятный BankCreateUpdateDto для методов POST / PUT)
* Поиск по банкам переделан с учетом запроса фронтов: теперь можно фильтровать поиск для кредитов и вкладов
* Добавлены интеграционные тесты для контроллера BankControllerTest

По тестам: сейчас покрытие ~80-90%, это достаточно для нас или хотим делать прям отдельно контроллер / сервис / репозиторий?
Почему спрашиваю, у нас достаточно простая CRUD логика пока реализована, кажется, что интеграционные тесты нормально справляются в целом. 

<img width="680" alt="Screenshot 2024-01-11 at 18 29 42" src="https://github.com/comparison-of-banking-products/cobp-backend/assets/118021621/c3ba097b-6877-4d8e-923d-d241aca49da4">

Получается PR закрывает полностью только таски 122 (фильтрация) и 124 (тесты банков), остальное в работе, завтра буду дальше смотреть, что можно править.

2024-01-11 23:19 UTC, MaximKostyolov commented on src/main/java/ru/cobp/backend/repository/bank/BankRepository.java
> +    Optional<Bank> findByBic(String bic);
Думаю здесь правильнее будет BankRepository extends JpaRepository<Bank, String> так как Id у нас теперь String. Тогда возможно и не нужны будут эти методы

2024-01-11 23:23 UTC, MaximKostyolov commented on src/main/java/ru/cobp/backend/dto/credit/NewCreditDto.java
> +    private String banksBic;
Поправь пожалуйста на bankBic, а то в своей ветке уже поправил (по комментариям Алексея, также в CreditDto), потом конфликт будет

2024-01-12 10:13 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/repository/bank/BankRepository.java
> +    Optional<Bank> findByBic(String bic);
точно, спасибо, что заметил! исправил

2024-01-12 10:13 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/dto/credit/NewCreditDto.java
> +    private String banksBic;
исправил

2024-01-12 12:20 UTC, alex-blag requested changes

2024-01-12 12:20 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
not found?

2024-01-12 12:21 UTC, alex-blag commented
По поводу:

"
По тестам: сейчас покрытие ~80-90%, это достаточно для нас или хотим делать прям отдельно контроллер / сервис / репозиторий?
Почему спрашиваю, у нас достаточно простая CRUD логика пока реализована, кажется, что интеграционные тесты нормально справляются в целом.
"

Единого стиля уже не выработаем, пожалуй, так что можно по собственному разумению достаточности делать :)

2024-01-12 12:27 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
no content должен быть) извиняюсь, опечатка, исправил

2024-01-12 12:29 UTC, alex-blag approved these changes

2024-01-13 00:05 UTC, MaximKostyolov submitted a review, later dismissed

2024-01-15 11:27 UTC, nkorzh commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +            summary = "Удалить банк по БИК номеру",
nit: не уверен что с тз бизнес-логики этот метод нужен но если вы так хотите то окей

2024-01-15 11:38 UTC, nkorzh reviewed
> По тестам: сейчас покрытие ~80-90%, это достаточно для нас или хотим делать прям отдельно контроллер / сервис / репозиторий?

не старайтесь гнаться за покрытием, это не так важно
важно чтобы тесты проверяли действительно значимые вещи

jfyi: на одном старом проекте у нас было выставлено целевое значение покрытия для ПР-а – 80%

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +        checkIfBankExistsByBic(newBank.getBic());
вроде уже писал но: если есть unique в схеме бд то проверять что банк уже существует нет необходимости

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +        }
хочется сделать update внутри маппера

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +    public Bank getBankByBicOrThrowException(String bic) {
nit: get-нотация обычно подразумевает что при отсутствии сущности бросается исключение
кстати чем не подошел стандартный getById метод? (если хотите свое исключение – пожалуйста)

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +        bankRepository.deleteById(bic);
можно кидать исключение если rowCount был == 0, полный гет может быть дорогим если сущность тяжелая

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +    public List<Bank> getAll(BankSort sort) {
контракт метода с null выглядит не очень надежно
я бы сделал getAll() и getAll(sort)

2024-01-15 11:38 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
> +            BooleanExpression expression;
expression -> predicate скорее

2024-01-15 19:06 UTC, mdemidkin1992 commented
Комменты ревьюера пометил как резолвд, чтобы можно было делать мерж, завтра добавлю по ним правки

2024-01-15 20:17 UTC, merged