feat: add credit parametrs(creditOnline, onlineApprove, collateral)
comparison-of-banking-products/cobp-backend pull request #139
Opened 2024-01-16 19:44 UTC by MaximKostyolov

2024-01-16 19:57 UTC, alex-blag requested changes
В дата-файле нужно какое-то разнообразие в новых параметрах :)

2024-01-16 19:57 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/credit/CreditController.java
> +            @RequestParam(required = false) @Parameter(description = "Подтверждение онлайн") Boolean onlineApprove,
"Получение без посещения банка" - так ПМ написала, ну - это дело вкуса, на твое усмотрение :)

2024-01-16 19:58 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/credit/CreditController.java
> +            @RequestParam(required = false) @Parameter(description = "Подтверждение онлайн") Boolean onlineApprove,
Это по поводу этого было: "Рассмотрение онлайн"

2024-01-17 08:17 UTC, alex-blag approved these changes

2024-01-17 09:43 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/dto/credit/CreditDto.java
>      private String paymentType;
Не хотим ли мы передавать сразу enum, чтобы потом отдельным методом toPaymentType() String не конвертировать? Также будет исключен вариант запроса с некорректным параметром, т.к. в сваггере будет видно.

2024-01-17 09:43 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
>      private Credit toCredit(NewCreditDto newCreditDto, Bank bank, Currency currency) {
Возможно маппинг стоит проводить в маппере? 
Если проблема с полями Bank и Credit, в маппере можно поставить ignore, а тут уже их присвоить. 
Тогда не придется через конструктор создавать сущность, который сложно читать из-за количества параметров

2024-01-17 09:43 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
>      private PaymentType toPaymentType(String paymentType) {
вот от этого метода на мой взгляд можно отказаться, если передавать сразу enum

2024-01-17 16:40 UTC, closed without merging