Fix: валюты и ревью 129
comparison-of-banking-products/cobp-backend pull request #146
Opened 2024-01-18 11:45 UTC by mdemidkin1992

2024-01-18 17:59 UTC, alex-blag requested changes

2024-01-18 17:59 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +@CrossOrigin(origins = "*")
Ранее был добавлен глобал корс конфиг, на уровне контроллеров более не нужен

2024-01-18 17:59 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/currency/CurrencyController.java
> +@CrossOrigin(origins = "*")
Ранее был добавлен глобал корс конфиг, на уровне контроллеров более не нужен

2024-01-19 06:39 UTC, MaximKostyolov commented on src/test/java/ru/cobp/backend/controller/currency/CurrencyControllerTest.java
> +    @Test
Название тестов в этом классе следует поменять. Вот что ревьюер написал мне по поводу CreditControllerTest: 

Имена тестов должны описывать поведение тестируемого объекта и условия для проявления такого поведения. В идеале список имен тестов должен служить краткой документацией к тестируемому классу/endpoint-у.

Форматы имени теста 

should<действие>When<условия>, например: shouldThrowWhenMoonIsFull
Если в одном файле тестируется много разных методов класса, и из названия теста вида should<действие>When<условия> не очевидно, какой метод используется, можно указывать имя метода, например:
checkConfirmationCodeShouldThrowWhenMoonIsFull, getOrderHistoryShouldProvideOnlyEvenCheckpointsWhenMoonIsFull

2024-01-19 08:25 UTC, alex-blag requested changes

2024-01-19 08:25 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +        log.info("Получен POST запрос по эндпоинту /banks на добавление Bank {}.", newBankDto);
Кстати, для завершающих недель вижу правило: "Чистка" кода - удаляем отладочный код, вывод в консоль", - полагаю логгер можешь смело удалять :)

2024-01-19 08:28 UTC, alex-blag commented on src/test/java/ru/cobp/backend/controller/currency/CurrencyControllerTest.java
> +    @Test
Я такие названия писал, например, тоже проходит - whenGetCalculatedDeposits_expectCalculatedDepositResponseDtos

Тема холиварная :) https://dzone.com/articles/7-popular-unit-test-naming

2024-01-19 09:17 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +        log.info("Получен POST запрос по эндпоинту /banks на добавление Bank {}.", newBankDto);
Не совсем согласен, что логи в проде не нужны, но если у вас так принято – ок)

2024-01-19 09:18 UTC, merged

2024-01-19 09:23 UTC, alex-blag commented on src/main/java/ru/cobp/backend/controller/bank/BankController.java
> +        log.info("Получен POST запрос по эндпоинту /banks на добавление Bank {}.", newBankDto);
Если не ошибаюсь, то логгировать вызовы контроллера можно штатной опцией:

logging.level.org.springframework.web=INFO

логи, конечно же, нужны, но грамотные :)

2024-01-20 14:36 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
>          bankRepository.deleteById(bic);
я бы здесь проверил row_count возвращаемый deleteById

2024-01-20 14:36 UTC, nkorzh commented on src/test/java/ru/cobp/backend/controller/currency/CurrencyControllerTest.java
> +                        .content(objectMapper.writeValueAsString(createUpdateDto)))
вот это антипаттерн

посмотрите вот эту статью
https://programmerfriend.com/biggest-antipattern-webmvc-tests

2024-01-22 14:44 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
>          bankRepository.deleteById(bic);
Не до конца понял, что именно мы хотим проверить, что стандартный метод JPA отработал корректно и удалил сущность по id (т.е. row_count == 1)? Или наоборот, что удалил несколько сущностей (напомню, что bic у нас уникальный, и такого по идее быть не может)? Или что он не отработал и row_count == 0.

Также смущает формулировка "возвращаемый deleteById", поскольку метод void. Нам надо написать кастомный JPA метод?

Можно, пожалуйста, добавить контекста комментарию, без него непонятно, что хотим исправить.

2024-01-24 13:34 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
>          bankRepository.deleteById(bic);
В репозитории можно объявить метод
```
long deleteById(String bic);
```
который будет возвращать количество удаленных банков

Если число 0, значит такого банка не было
https://www.baeldung.com/spring-data-jpa-deleteby

2024-01-24 15:57 UTC, mdemidkin1992 commented on src/main/java/ru/cobp/backend/service/bank/BankServiceImpl.java
>          bankRepository.deleteById(bic);
Спасибо большое, так гораздо понятнее стало, исправим)