feat: add credits
comparison-of-banking-products/cobp-backend pull request #18
Opened 2023-12-07 12:37 UTC by MaximKostyolov

feat: add credits (model, dto, part of controller), models of bank, currency, payment type to connect entity

2023-12-07 12:47 UTC, alex-blag commented on src/main/java/ru/cobp/backend/bank/entity/Bank.java
> +}
Вставляй пустую последнюю строку

2023-12-07 12:48 UTC, alex-blag commented on src/main/java/ru/cobp/backend/credit/dto/CreditCalculatorDto.java
> +public class CreditCalculatorDto {
Говорили о том, что калькулятор надо убрать из Кредитов, сделаем отдельный ресурс

2023-12-07 12:51 UTC, alex-blag commented on src/main/java/ru/cobp/backend/credit/service/CreditService.java
> +public interface CreditService {
Возможно надо использовать CreditPublicService, а CreditService будет общий

2023-12-07 12:52 UTC, alex-blag commented on src/main/java/ru/cobp/backend/currency/entity/Currency.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
num - это цифровой код из справочника, автоматически генерироваться не будет

2023-12-07 13:46 UTC, alex-blag requested changes

2023-12-07 13:46 UTC, alex-blag commented on src/main/java/ru/cobp/backend/currency/entity/Currency.java
> +}
Строку

2023-12-08 13:18 UTC, alex-blag approved these changes

2023-12-08 13:44 UTC, AKnazzz approved these changes

2023-12-08 13:49 UTC, merged