feat-add-bank
comparison-of-banking-products/cobp-backend pull request #29
Opened 2023-12-10 15:24 UTC by Elina1313

2023-12-11 06:11 UTC, alex-blag requested changes

2023-12-11 06:11 UTC, alex-blag commented on src/main/java/ru/cobp/backend/bank/controller/BankController.java
> +    public ResponseEntity<BankDto> create(@RequestBody BankDto bankDto) {
Не понятен выбор ResponseEntity;
Договорились использовать NewBankDto для создания новых объектов

2023-12-11 06:11 UTC, alex-blag commented on src/main/java/ru/cobp/backend/bank/service/BankService.java
> +    BankDto update(Long bankId, BankDto updBank);
У Bank нет id - есть bic

2023-12-11 06:11 UTC, alex-blag commented on src/main/java/ru/cobp/backend/bank/service/BankServiceImpl.java
> +        return null;
Для незаконченных методов не используй: return null;

Используй: throw new UnsupportedOperationException("Not implemented yet");

2023-12-14 19:19 UTC, Elina1313 commented on src/main/java/ru/cobp/backend/bank/controller/BankController.java
> +    public ResponseEntity<BankDto> create(@RequestBody BankDto bankDto) {
поправила

2023-12-14 19:19 UTC, Elina1313 commented on src/main/java/ru/cobp/backend/bank/service/BankService.java
> +    BankDto update(Long bankId, BankDto updBank);
поправила

2023-12-14 19:20 UTC, Elina1313 commented on src/main/java/ru/cobp/backend/bank/service/BankServiceImpl.java
> +        return null;
поправила

2023-12-15 06:43 UTC, merged