Feat add credits
comparison-of-banking-products/cobp-backend pull request #55
Opened 2023-12-21 01:29 UTC by MaximKostyolov

feat: add credits (refactor credit contoller, credit service, add payment type)

2023-12-21 08:10 UTC, alex-blag requested changes

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/exception/ErrorHandler.java
> +        String reason = "Incorrect payment type";
Или даже не месседж, а ризон - "Incorrect payment type", - вот это сообщим и время, будет достаточно

Код будет в ответе, а месседж - это внутренняя кухня

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/exception/ErrorHandler.java
> +        return new ResponseEntity<>(errorResponse, httpStatus);
а вот логгирование здесь можно было добавить, нормально залоггируешь эксепшн, отправишь сухой ответ :)

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Скорее всего ментор скажет уточнить, тк сейчас не понятно

Ну, на твое усмотрение :)

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/model/credit/Credit.java
> +    private PaymentType paymentType;
лучше убери

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/model/credit/Credit.java
> +    public Credit(Bank bank, String name, String productUrl, Boolean isActive, Currency currency, Integer amountMin,
добавь аннотацию AllArgsConstructor, явный конструктор удали

2023-12-21 08:10 UTC, alex-blag commented on src/main/resources/schema.sql
> +    payment_type        VARCHAR(20)     NOT NULL,
убери

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/service/credit/CreditPublicServiceImpl.java
>  public class CreditPublicServiceImpl implements CreditPublicService {
Ментор написал, не нужно нам никаких админок и пабликов

2023-12-21 08:10 UTC, alex-blag commented on src/main/java/ru/cobp/backend/model/credit/PaymentType.java
> +public enum PaymentType {
все-таки убери :)

2023-12-22 10:09 UTC, MaximKostyolov commented on src/main/java/ru/cobp/backend/exception/ErrorHandler.java
> +        return new ResponseEntity<>(errorResponse, httpStatus);
Добавлю в дальнейшем

2023-12-22 10:54 UTC, closed without merging