merge: dev into main
comparison-of-banking-products/cobp-backend pull request #70
Opened 2023-12-22 13:01 UTC by alex-blag

2023-12-24 16:20 UTC, nkorzh requested changes
предлагаю добавить mapstruct – экономит много усилий

тестов нет, так жить очень тяжело

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +@Transactional()
nit: ()

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +        Iterable<Credit> credits = creditRepository.findAll(p, pageable);
не понял почему репозиторий тут отдает итератор

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +        return Utils.toList(credits);
я бы назвал iterableToList и положил бы в ListUtils или что-то такое

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +        }
```
var currency = Optional.ofNullable(params.getCurrencyNum())
  .map(currencyService::getById)
  .orElseGet(Currency::new);
```
а вообще эта логика просится внутрь buildQCreditPredicateByParams

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +        return creditRepository.findById(id).orElseThrow(() ->
чем плох getById ? он бросает исключение сам

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/credit/CreditServiceImpl.java
> +        }
это все просится в метод маппера
как сделать валидацию бик и валюты это отдельный вопрос

а нужен ли в целом такой метод? все ли эти поля надо уметь менять через update?

2023-12-24 16:20 UTC, nkorzh commented on src/main/java/ru/cobp/backend/service/currency/impl/CurrencyRatesServiceImpl.java
> +    @Scheduled(fixedDelay = 3_600_000)
обычно такое в конфиг выносят

2023-12-25 07:41 UTC, alex-blag commented on src/main/java/ru/cobp/backend/client/exchange/CbrDailyExchangeRatesClientImpl.java
> +                }
Верно, клиент должен вернуть данные в удобном для нас формате, не знаю по какой причине они хранят значения и разные номиналы для разной валюты - деление там для того, чтобы привести к одному номиналу, т.е. это штатная обработка полученных значений.

2023-12-25 08:56 UTC, merged